### ISSUE TITLE
Wrong Gardevoir abilities

### ISSUE THREAD

**Issue by flashymittens** [ckaznable/poke-data-cralwer#2]
Gardevoir is listed with ability Pixilate, except it’s the ability of Mega Gardevoir, while normal Gardevoir has Synchronize, Trace and Telepathy. Both wiki.52poke.com and www.serebii.net list abilities correctly from what I can see.

**Comment by ckaznable** [comment]
It looks like there's a problem with all the mega types. I'll get around to it. Thank you.

**Comment by ckaznable** [comment]
@flashymittens fixed.
